---

- name: Deploy new mindmaps version
  hosts: mindmaps
  remote_user: ec2-user

  tasks:

  - name: Ensure nginx, git and node are present
    ansible.builtin.dnf:
      name:
        - nginx-1.22.1
        - git
        - nodejs-18.12.1
      state: present
    become: true

  - name: Stop running nginx 
    ansible.builtin.systemd:
      state: stopped
      name: nginx
    become: true

  - name: Check nginx config
    ansible.builtin.shell:
      cmd: "cat /etc/nginx/mime.types | grep cache-manifest | wc -l"
    register: nginx_config_presence
  
  - name: Change config
    ansible.builtin.shell:
      cmd: "sed -i '$d' /etc/nginx/mime.types && printf \"\ttext/cache-manifest\tappcache;\n}\" >> /etc/nginx/mime.types"
    become: true
    when: mindmaps_latest.stdout | int == 0

  - name: Directory exists
    ansible.builtin.file:
      state: directory
      path: /mindmaps/app-old
  
  - name: Create fallback copy
    ansible.builtin.copy:
      src: /usr/share/nginx/html
      dest: /mindmaps/app-old
      remote_src: true
    become: true

  - name: Delete old version
    ansible.builtin.file:
      state: absent
      path: /usr/share/nginx/html
    become: true
  
  - name: Clone new version
    ansible.builtin.git:
      repo: https://github.com/apo-diod/mindmaps
      dest: /mindmaps/build
  
  - name: Build app
    ansible.builtin.shell:
      cmd: npm install && npm run build
      chdir: /mindmaps/build
  
  - name: Copy new app
    ansible.builtin.copy:
      src: /mindmaps/app/dist
      dest: /usr/share/nginx/html
      remote_src: true
    become: true
  
  - name: Start nginx
    ansible.builtin.systemd:
      state: started
      name: nginx
    become: true
  
  - name: Test app
    ansible.builtin.uri:
      url: "http://3.127.214.12/"
      method: GET
    register: result
    until: result.status == 200
    retries: 20
    delay: 30
  
  - name: Delete old and build files
    ansible.builtin.shell:
      cmd: "rm -rf /mindmaps/*"
    become: true
