---

- name: Deploy new mindmaps version
  hosts: localhost
  remote_user: hostadmin
  connection: local

  tasks:
    - name: Check docker version
      ansible.builtin.shell:
        cmd: docker version