---

- name: Deploy new mindmaps version
  hosts: 167.86.117.56
  remote_user: hostadmin

  tasks:
    - name: Check user
      debug:
        msg: "{{ ansible_user_id }}"
    - name: Check docker version
      ansible.builtin.shell:
        cmd: docker ps