---

- name: Deploy new mindmaps version
  hosts: loc
  remote_user: hostadmin

  tasks:
    - name: Create temp directory 
      ansible.builtin.file:
        state: directory
        path: /tmp/hostadmin/temp/
    