---

- name: Deploy new mindmaps version
  hosts: loc
  remote_user: hostadmin

  tasks:
    - name: Check user
      debug:
        msg: "{{ ansible_user_id }}"
    - name: Check docker version
      ansible.builtin.shell:
        cmd: docker version
      register: docker_ver
    - name: Check version
      debug:
        msg: "{{ docker_ver }}"